### Installing Light Gradient Boosting Machine

In [25]:
!pip install lightgbm

Collecting lightgbm
  Downloading lightgbm-4.6.0-py3-none-win_amd64.whl.metadata (17 kB)
Requirement already satisfied: numpy>=1.17.0 in C:\Users\CHANDRU DEIVANAYAGAN\AppData\Local\Programs\Python\Python313\Lib\site-packages (from lightgbm) (2.2.6)
Requirement already satisfied: scipy in C:\Users\CHANDRU DEIVANAYAGAN\AppData\Local\Programs\Python\Python313\Lib\site-packages (from lightgbm) (1.16.2)
Downloading lightgbm-4.6.0-py3-none-win_amd64.whl (1.5 MB)
   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
   ---------------------------- ----------- 1.0/1.5 MB 10.1 MB/s eta 0:00:01
   ---------------------------------------- 1.5/1.5 MB 8.8 MB/s  0:00:00
Installing collected packages: lightgbm
Successfully installed lightgbm-4.6.0

### Import necessary libraries

In [26]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report,precision_score,recall_score
from sklearn.ensemble import AdaBoostClassifier,GradientBoostingClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
import warnings
warnings.filterwarnings("ignore")

### Import dataset

In [13]:
credit_card_data = pd.read_csv("credit_card_clean.csv")

In [14]:
credit_card_data.head()

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_1,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,DEFAULT
0,1,20000.0,female,university,married,24,2,2,-1,-1,...,0.0,0.0,0.0,0.0,689.0,0.0,0.0,0.0,0.0,1
1,2,120000.0,female,university,single,26,-1,2,0,0,...,3272.0,3455.0,3261.0,0.0,1000.0,1000.0,1000.0,0.0,2000.0,1
2,3,90000.0,female,university,single,34,0,0,0,0,...,14331.0,14948.0,15549.0,1518.0,1500.0,1000.0,1000.0,1000.0,5000.0,0
3,4,50000.0,female,university,married,37,0,0,0,0,...,28314.0,28959.0,29547.0,2000.0,2019.0,1200.0,1100.0,1069.0,1000.0,0
4,5,50000.0,male,university,married,57,-1,0,-1,0,...,20940.0,19146.0,19131.0,2000.0,36681.0,10000.0,9000.0,689.0,679.0,0

### Data Understanding

### Description document

# ------------
# ----------
# ----------
# ---------
# ---------
# ----------

In [18]:
credit_card_data.tail()

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_1,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,DEFAULT
29995,29996,220000.0,male,highschool,married,39,0,0,0,0,...,88004.0,31237.0,15980.0,8500.0,20000.0,5003.0,3047.0,5000.0,1000.0,0
29996,29997,150000.0,male,highschool,single,43,-1,-1,-1,-1,...,8979.0,5190.0,0.0,1837.0,3526.0,8998.0,129.0,0.0,0.0,0
29997,29998,30000.0,male,university,single,37,4,3,2,-1,...,20878.0,20582.0,19357.0,0.0,0.0,22000.0,4200.0,2000.0,3100.0,1
29998,29999,80000.0,male,highschool,married,41,1,-1,0,0,...,52774.0,11855.0,48944.0,85900.0,3409.0,1178.0,1926.0,52964.0,1804.0,1
29999,30000,50000.0,male,university,married,46,0,0,0,0,...,36535.0,32428.0,15313.0,2078.0,1800.0,1430.0,1000.0,1000.0,1000.0,1

In [19]:
credit_card_data.shape

(30000, 25)

In [20]:
credit_card_data.dtypes

ID             int64
LIMIT_BAL    float64
SEX           object
EDUCATION     object
MARRIAGE      object
AGE            int64
PAY_1          int64
PAY_2          int64
PAY_3          int64
PAY_4          int64
PAY_5          int64
PAY_6          int64
BILL_AMT1    float64
BILL_AMT2    float64
BILL_AMT3    float64
BILL_AMT4    float64
BILL_AMT5    float64
BILL_AMT6    float64
PAY_AMT1     float64
PAY_AMT2     float64
PAY_AMT3     float64
PAY_AMT4     float64
PAY_AMT5     float64
PAY_AMT6     float64
DEFAULT        int64
dtype: object

In [21]:
credit_card_data.isna().sum()

ID           0
LIMIT_BAL    0
SEX          0
EDUCATION    0
MARRIAGE     0
AGE          0
PAY_1        0
PAY_2        0
PAY_3        0
PAY_4        0
PAY_5        0
PAY_6        0
BILL_AMT1    0
BILL_AMT2    0
BILL_AMT3    0
BILL_AMT4    0
BILL_AMT5    0
BILL_AMT6    0
PAY_AMT1     0
PAY_AMT2     0
PAY_AMT3     0
PAY_AMT4     0
PAY_AMT5     0
PAY_AMT6     0
DEFAULT      0
dtype: int64

In [22]:
credit_card_data.shape

(30000, 25)

### Data Preparation
#### 1. data cleaning
#### 2. data transformation

In [24]:
del credit_card_data['ID']

### Label encoder processing

In [28]:
credit_card_data.head()

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_1,PAY_2,PAY_3,PAY_4,PAY_5,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,DEFAULT
0,20000.0,female,university,married,24,2,2,-1,-1,-2,...,0.0,0.0,0.0,0.0,689.0,0.0,0.0,0.0,0.0,1
1,120000.0,female,university,single,26,-1,2,0,0,0,...,3272.0,3455.0,3261.0,0.0,1000.0,1000.0,1000.0,0.0,2000.0,1
2,90000.0,female,university,single,34,0,0,0,0,0,...,14331.0,14948.0,15549.0,1518.0,1500.0,1000.0,1000.0,1000.0,5000.0,0
3,50000.0,female,university,married,37,0,0,0,0,0,...,28314.0,28959.0,29547.0,2000.0,2019.0,1200.0,1100.0,1069.0,1000.0,0
4,50000.0,male,university,married,57,-1,0,-1,0,0,...,20940.0,19146.0,19131.0,2000.0,36681.0,10000.0,9000.0,689.0,679.0,0

In [29]:
le = LabelEncoder()
credit_card_data["SEX"] = le.fit_transform(credit_card_data["SEX"])
credit_card_data["EDUCATION"] = le.fit_transform(credit_card_data["EDUCATION"])
credit_card_data["MARRIAGE"] = le.fit_transform(credit_card_data["MARRIAGE"])

In [30]:
credit_card_data.head()

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_1,PAY_2,PAY_3,PAY_4,PAY_5,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,DEFAULT
0,20000.0,0,3,0,24,2,2,-1,-1,-2,...,0.0,0.0,0.0,0.0,689.0,0.0,0.0,0.0,0.0,1
1,120000.0,0,3,2,26,-1,2,0,0,0,...,3272.0,3455.0,3261.0,0.0,1000.0,1000.0,1000.0,0.0,2000.0,1
2,90000.0,0,3,2,34,0,0,0,0,0,...,14331.0,14948.0,15549.0,1518.0,1500.0,1000.0,1000.0,1000.0,5000.0,0
3,50000.0,0,3,0,37,0,0,0,0,0,...,28314.0,28959.0,29547.0,2000.0,2019.0,1200.0,1100.0,1069.0,1000.0,0
4,50000.0,1,3,0,57,-1,0,-1,0,0,...,20940.0,19146.0,19131.0,2000.0,36681.0,10000.0,9000.0,689.0,679.0,0

In [32]:
X = credit_card_data.drop("DEFAULT",axis=1)

y = credit_card_data['DEFAULT']

In [33]:
## Model building

In [36]:
X_train,X_test,y_train,y_test = train_test_split(X,y,train_size=0.80,shuffle=True,random_state=101,stratify=y)

In [37]:
X.shape,y.shape

((30000, 23), (30000,))

In [38]:
X_train.shape

(24000, 23)

In [40]:
X_test.shape

(6000, 23)

### Model Training

### Training time analysis

In [42]:
adab_classifier = AdaBoostClassifier()
gdb_classifier = GradientBoostingClassifier(n_estimators=50)
xgb_classifier = XGBClassifier(n_estimators=50)
lgb_classifier = LGBMClassifier(n_estimators=50)

In [43]:
%%time
adab_classifier.fit(X_train,y_train)

CPU times: total: 1.91 s
Wall time: 1.91 s

AdaBoostClassifier()

In [45]:
%%time
gdb_classifier.fit(X_train,y_train)

CPU times: total: 4.66 s
Wall time: 4.71 s

GradientBoostingClassifier(n_estimators=50)

In [47]:
%%time
xgb_classifier.fit(X_train,y_train)

CPU times: total: 1.12 s
Wall time: 180 ms

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=50,
              n_jobs=None, num_parallel_tree=None, ...)

In [50]:
%%time
lgb_classifier.fit(X_train,y_train)

[LightGBM] [Info] Number of positive: 5309, number of negative: 18691
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000571 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 3258
[LightGBM] [Info] Number of data points in the train set: 24000, number of used features: 23
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.221208 -> initscore=-1.258639
[LightGBM] [Info] Start training from score -1.258639
CPU times: total: 547 ms
Wall time: 208 ms

LGBMClassifier(n_estimators=50)

### Model_prediction

### 7. Model testing

In [57]:
y_pred_adab = adab_classifier.predict(X_test)
y_pred_gdb = gdb_classifier.predict(X_test)
y_pred_xgb = xgb_classifier.predict(X_test)
y_pred_lgb = lgb_classifier.predict(X_test)

### Model evaluation

### Ada-boost - evaluation

In [63]:
print("Accuracy-Score:",round(accuracy_score(y_test,y_pred_adab),4))
print("Precision-Score",round(precision_score(y_test,y_pred_adab),4))
print("Recall-Score:",round(recall_score(y_test,y_pred_adab),4))
print("Confusion-Matrix:\n",confusion_matrix(y_test,y_pred_adab))

Accuracy-Score: 0.8227
Precision-Score 0.7039
Recall-Score: 0.3421
Confusion-Matrix:
 [[4482  191]
 [ 873  454]]

### gradient-boosting evaluation

In [66]:
print("Accuracy-Score:",round(accuracy_score(y_test,y_pred_gdb),4))
print("Precision-Score",round(precision_score(y_test,y_pred_gdb),4))
print("Recall-Score:",round(recall_score(y_test,y_pred_gdb),4))
print("Confusion-Matrix:\n",confusion_matrix(y_test,y_pred_gdb))

Accuracy-Score: 0.8282
Precision-Score 0.7108
Recall-Score: 0.376
Confusion-Matrix:
 [[4470  203]
 [ 828  499]]

### Xgboost-evaluation

In [68]:
print("Accuracy-Score:",round(accuracy_score(y_test,y_pred_xgb),4))
print("Precision-Score",round(precision_score(y_test,y_pred_xgb),4))
print("Recall-Score:",round(recall_score(y_test,y_pred_xgb),4))
print("Confusion-Matrix:\n",confusion_matrix(y_test,y_pred_xgb))

Accuracy-Score: 0.8213
Precision-Score 0.6768
Recall-Score: 0.3677
Confusion-Matrix:
 [[4440  233]
 [ 839  488]]

### Light Gradient-boosting evaluation

In [70]:
print("Accuracy-Score:",round(accuracy_score(y_test,y_pred_lgb),4))
print("Precision-Score",round(precision_score(y_test,y_pred_lgb),4))
print("Recall-Score:",round(recall_score(y_test,y_pred_lgb),4))
print("Confusion-Matrix:\n",confusion_matrix(y_test,y_pred_lgb))

Accuracy-Score: 0.8245
Precision-Score 0.6851
Recall-Score: 0.3821
Confusion-Matrix:
 [[4440  233]
 [ 820  507]]

### THE END!!!

### FEATURE IMPORTANCE

### ADABOOST --- GRADIENT BOOSTING --- EXTREME GRADIENT BOOSTING --- LIGHT GRADIENT BOOSTING MACHINES