In [41]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,precision_score,recall_score,confusion_matrix
from sklearn.ensemble import AdaBoostClassifier,GradientBoostingClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from sklearn.tree import DecisionTreeClassifier
import warnings
warnings.filterwarnings("ignore")

In [2]:
credit_card_data = pd.read_csv("credit_card_clean.csv")

In [3]:
credit_card_data.head()

   ID  LIMIT_BAL     SEX   EDUCATION MARRIAGE  AGE  ...  PAY_AMT2  PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  DEFAULT
0   1    20000.0  female  university  married   24  ...     689.0       0.0       0.0       0.0       0.0        1
1   2   120000.0  female  university   single   26  ...    1000.0    1000.0    1000.0       0.0    2000.0        1
2   3    90000.0  female  university   single   34  ...    1500.0    1000.0    1000.0    1000.0    5000.0        0
3   4    50000.0  female  university  married   37  ...    2019.0    1200.0    1100.0    1069.0    1000.0        0
4   5    50000.0    male  university  married   57  ...   36681.0   10000.0    9000.0     689.0     679.0        0

[5 rows x 25 columns]

In [4]:
credit_card_data.shape

(30000, 25)

In [5]:
credit_card_data.dtypes

ID             int64
LIMIT_BAL    float64
SEX           object
EDUCATION     object
MARRIAGE      object
AGE            int64
PAY_1          int64
PAY_2          int64
PAY_3          int64
PAY_4          int64
PAY_5          int64
PAY_6          int64
BILL_AMT1    float64
BILL_AMT2    float64
BILL_AMT3    float64
BILL_AMT4    float64
BILL_AMT5    float64
BILL_AMT6    float64
PAY_AMT1     float64
PAY_AMT2     float64
PAY_AMT3     float64
PAY_AMT4     float64
PAY_AMT5     float64
PAY_AMT6     float64
DEFAULT        int64
dtype: object

In [7]:
credit_card_data.isna().sum()

ID           0
LIMIT_BAL    0
SEX          0
EDUCATION    0
MARRIAGE     0
AGE          0
PAY_1        0
PAY_2        0
PAY_3        0
PAY_4        0
PAY_5        0
PAY_6        0
BILL_AMT1    0
BILL_AMT2    0
BILL_AMT3    0
BILL_AMT4    0
BILL_AMT5    0
BILL_AMT6    0
PAY_AMT1     0
PAY_AMT2     0
PAY_AMT3     0
PAY_AMT4     0
PAY_AMT5     0
PAY_AMT6     0
DEFAULT      0
dtype: int64

In [8]:
le = LabelEncoder()

In [9]:
credit_card_data["SEX"] = le.fit_transform(credit_card_data["SEX"])
credit_card_data["EDUCATION"] = le.fit_transform(credit_card_data["EDUCATION"])
credit_card_data["MARRIAGE"] = le.fit_transform(credit_card_data["MARRIAGE"])

In [10]:
credit_card_data.head()

   ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  ...  PAY_AMT2  PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  DEFAULT
0   1    20000.0    0          3         0   24  ...     689.0       0.0       0.0       0.0       0.0        1
1   2   120000.0    0          3         2   26  ...    1000.0    1000.0    1000.0       0.0    2000.0        1
2   3    90000.0    0          3         2   34  ...    1500.0    1000.0    1000.0    1000.0    5000.0        0
3   4    50000.0    0          3         0   37  ...    2019.0    1200.0    1100.0    1069.0    1000.0        0
4   5    50000.0    1          3         0   57  ...   36681.0   10000.0    9000.0     689.0     679.0        0

[5 rows x 25 columns]

In [12]:
X = credit_card_data.drop(labels="DEFAULT",axis=1)
y = credit_card_data["DEFAULT"]

In [14]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.20,shuffle=True,random_state=101,stratify=y)

In [15]:
adaboost_classifier = AdaBoostClassifier()

adaboost_classifier.fit(X_train,y_train)

AdaBoostClassifier()

In [16]:
y_pred_adaboost = adaboost_classifier.predict(X_test)

In [17]:
print("Accuracy Score:",round(accuracy_score(y_test,y_pred_adaboost),4))
print("Precision Score:",round(precision_score(y_test,y_pred_adaboost),4))
print("Recall Score:",round(recall_score(y_test,y_pred_adaboost),4))
print("Confusion Matrix:\n",confusion_matrix(y_test,y_pred_adaboost))

Accuracy Score: 0.8227
Precision Score: 0.7039
Recall Score: 0.3421
Confusion Matrix:
 [[4482  191]
 [ 873  454]]

In [19]:
gradient_boost_classifier = GradientBoostingClassifier()

gradient_boost_classifier.fit(X_train,y_train)

GradientBoostingClassifier()

In [22]:
y_pred_grad_boost = gradient_boost_classifier.predict(X_test)

In [23]:
print("Accuracy Score:",round(accuracy_score(y_test,y_pred_grad_boost),4))
print("Precision Score:",round(precision_score(y_test,y_pred_grad_boost),4))
print("Recall Score:",round(recall_score(y_test,y_pred_grad_boost),4))
print("Confusion Matrix:\n",confusion_matrix(y_test,y_pred_grad_boost))

Accuracy Score: 0.8257
Precision Score: 0.6949
Recall Score: 0.3775
Confusion Matrix:
 [[4453  220]
 [ 826  501]]

In [24]:
Extreme_grad_boost = XGBClassifier()

Extreme_grad_boost.fit(X_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, ...)

In [25]:
y_pred_XGB = Extreme_grad_boost.predict(X_test)

In [26]:
print("Accuracy Score:",round(accuracy_score(y_test,y_pred_XGB),4))
print("Precision Score:",round(precision_score(y_test,y_pred_XGB),4))
print("Recall Score:",round(recall_score(y_test,y_pred_XGB),4))
print("Confusion Matrix:\n",confusion_matrix(y_test,y_pred_XGB))

Accuracy Score: 0.8197
Precision Score: 0.6577
Recall Score: 0.3851
Confusion Matrix:
 [[4407  266]
 [ 816  511]]

In [27]:
light_grad_boost = LGBMClassifier()

light_grad_boost.fit(X_train,y_train)

[LightGBM] [Info] Number of positive: 5309, number of negative: 18691
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000421 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 3513
[LightGBM] [Info] Number of data points in the train set: 24000, number of used features: 24
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.221208 -> initscore=-1.258639
[LightGBM] [Info] Start training from score -1.258639

LGBMClassifier()

In [28]:
y_pred_lgbm = light_grad_boost.predict(X_test)

In [29]:
print("Accuracy Score:",round(accuracy_score(y_test,y_pred_lgbm),4))
print("Precision Score:",round(precision_score(y_test,y_pred_lgbm),4))
print("Recall Score:",round(recall_score(y_test,y_pred_lgbm),4))
print("Confusion Matrix:\n",confusion_matrix(y_test,y_pred_lgbm))

Accuracy Score: 0.8252
Precision Score: 0.6883
Recall Score: 0.3828
Confusion Matrix:
 [[4443  230]
 [ 819  508]]

In [30]:
adaboost_classifier.feature_importances_

array([0.        , 0.03802969, 0.        , 0.        , 0.        ,
       0.01727303, 0.56770294, 0.01173904, 0.06273664, 0.        ,
       0.03726443, 0.01519855, 0.        , 0.03588099, 0.        ,
       0.        , 0.        , 0.        , 0.09865308, 0.04805402,
       0.04581527, 0.01708587, 0.00456645, 0.        ])

In [31]:
gradient_boost_classifier.feature_importances_

array([0.01207515, 0.02691146, 0.001919  , 0.00165635, 0.00181012,
       0.01122708, 0.6193154 , 0.08124747, 0.03533332, 0.01658804,
       0.0221285 , 0.01474949, 0.03372279, 0.01041226, 0.00580543,
       0.00701354, 0.00612397, 0.00658765, 0.01509464, 0.02480945,
       0.02426089, 0.00730306, 0.00532621, 0.00857876])

In [32]:
Extreme_grad_boost.feature_importances_

array([0.01859272, 0.02341513, 0.01764883, 0.02031771, 0.01855538,
       0.01853415, 0.3567957 , 0.12027995, 0.03681114, 0.04167915,
       0.04332976, 0.02740121, 0.02403008, 0.02076259, 0.0191951 ,
       0.0210418 , 0.01846749, 0.01946975, 0.0210276 , 0.0247937 ,
       0.02648197, 0.02182584, 0.0199491 , 0.01959411], dtype=float32)

In [33]:
light_grad_boost.feature_importances_

array([254, 206,  32,  56,  36, 197,  89,  47,  53,  41,  40,  53, 239,
       143,  95, 111, 121, 151, 179, 201, 177, 149, 156, 174], dtype=int32)

In [34]:
feature_importance_list = pd.DataFrame(data={
    "Features":X.columns,
    "Ada-boost":adaboost_classifier.feature_importances_,
    "Grad-boost":gradient_boost_classifier.feature_importances_,
    "XGBoost":Extreme_grad_boost.feature_importances_,
    "LGBM":light_grad_boost.feature_importances_
})

In [35]:
feature_importance_list.head(11)

     Features  Ada-boost  Grad-boost   XGBoost  LGBM
0          ID   0.000000    0.012075  0.018593   254
1   LIMIT_BAL   0.038030    0.026911  0.023415   206
2         SEX   0.000000    0.001919  0.017649    32
3   EDUCATION   0.000000    0.001656  0.020318    56
4    MARRIAGE   0.000000    0.001810  0.018555    36
5         AGE   0.017273    0.011227  0.018534   197
6       PAY_1   0.567703    0.619315  0.356796    89
7       PAY_2   0.011739    0.081247  0.120280    47
8       PAY_3   0.062737    0.035333  0.036811    53
9       PAY_4   0.000000    0.016588  0.041679    41
10      PAY_5   0.037264    0.022128  0.043330    40

In [36]:
adaboost_top_features = feature_importance_list.sort_values(by="Ada-boost",ascending=False)

In [38]:
gradboost_top_features = feature_importance_list.sort_values(by="Grad-boost",ascending=False)
xgboost_top_features = feature_importance_list.sort_values(by="XGBoost",ascending=False)
lgboost_top_features = feature_importance_list.sort_values(by="LGBM",ascending=False)

In [40]:
adaboost_top_features.head(11)

     Features  Ada-boost  Grad-boost   XGBoost  LGBM
6       PAY_1   0.567703    0.619315  0.356796    89
18   PAY_AMT1   0.098653    0.015095  0.021028   179
8       PAY_3   0.062737    0.035333  0.036811    53
19   PAY_AMT2   0.048054    0.024809  0.024794   201
20   PAY_AMT3   0.045815    0.024261  0.026482   177
1   LIMIT_BAL   0.038030    0.026911  0.023415   206
10      PAY_5   0.037264    0.022128  0.043330    40
13  BILL_AMT2   0.035881    0.010412  0.020763   143
5         AGE   0.017273    0.011227  0.018534   197
21   PAY_AMT4   0.017086    0.007303  0.021826   149
11      PAY_6   0.015199    0.014749  0.027401    53