In [33]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from sklearn.linear_model import LinearRegression,LogisticRegression
from sklearn.model_selection import train_test_split
import statsmodels.formula.api as smf
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score,mean_absolute_error,mean_squared_error,root_mean_squared_error,r2_score

In [2]:
cars_data = pd.read_csv(filepath_or_buffer="Cars.csv")

In [3]:
cars_data.shape

(81, 5)

In [4]:
cars_data.dtypes

HP       int64
MPG    float64
VOL      int64
SP     float64
WT     float64
dtype: object

In [5]:
cars_data.head()

   HP        MPG  VOL          SP         WT
0  49  53.700681   89  104.185353  28.762059
1  55  50.013401   92  105.461264  30.466833
2  55  50.013401   92  105.461264  30.193597
3  70  45.696322   92  113.461264  30.632114
4  53  50.504232   92  104.461264  29.889149

In [6]:
cars_data.isnull().sum()

HP     0
MPG    0
VOL    0
SP     0
WT     0
dtype: int64

In [7]:
cars_data.describe()

               HP        MPG         VOL          SP         WT
count   81.000000  81.000000   81.000000   81.000000  81.000000
mean   117.469136  34.422076   98.765432  121.540272  32.412577
std     57.113502   9.131445   22.301497   14.181432   7.492813
min     49.000000  12.101263   50.000000   99.564907  15.712859
25%     84.000000  27.856252   89.000000  113.829145  29.591768
50%    100.000000  35.152727  101.000000  118.208698  32.734518
75%    140.000000  39.531633  113.000000  126.404312  37.392524
max    322.000000  53.700681  160.000000  169.598513  52.997752

In [8]:
cars_data

     HP        MPG  VOL          SP         WT
0    49  53.700681   89  104.185353  28.762059
1    55  50.013401   92  105.461264  30.466833
2    55  50.013401   92  105.461264  30.193597
3    70  45.696322   92  113.461264  30.632114
4    53  50.504232   92  104.461264  29.889149
..  ...        ...  ...         ...        ...
76  322  36.900000   50  169.598513  16.132947
77  238  19.197888  115  150.576579  37.923113
78  263  34.000000   50  151.598513  15.769625
79  295  19.833733  119  167.944460  39.423099
80  236  12.101263  107  139.840817  34.948615

[81 rows x 5 columns]

In [9]:
X = cars_data.drop(labels="MPG",axis=1)

In [10]:
y=cars_data["MPG"]

In [11]:
linear_model = LinearRegression()

In [13]:
linear_model.fit(X,y)

LinearRegression()

In [14]:
linear_model.coef_

array([-0.20544372, -0.33605084,  0.39562692,  0.40057409])

In [15]:
linear_model.intercept_

np.float64(30.67733585215165)

In [16]:
y_pred = linear_model.predict(X)

In [17]:
y_pred

array([43.44193477, 42.38879289, 42.27934147, 42.53835981, 42.17264802,
       43.02061916, 42.32536062, 48.07621852, 48.28120247, 40.79122814,
       41.52153227, 47.80956747, 39.95980269, 41.52757889, 41.76632332,
       41.6181448 , 41.15094046, 47.98605515, 41.30861046, 37.87127922,
       38.57706414, 37.35199705, 37.89770285, 39.5625144 , 39.93380662,
       46.73870908, 35.48165898, 38.78152504, 38.24861192, 36.00285298,
       34.84603989, 37.21630246, 37.13919796, 34.82541399, 37.22361389,
       37.53950097, 39.27144845, 38.24219888, 38.54286458, 35.9391722 ,
       34.2129755 , 35.36313259, 37.50473376, 38.07998482, 35.79651664,
       36.2613377 , 34.21826465, 35.59393404, 36.91805291, 33.31108154,
       33.21313413, 33.3023649 , 29.19864884, 27.52358579, 28.3207133 ,
       28.56722621, 35.81583602, 33.02108459, 35.37334971, 32.29909503,
       29.87685849, 28.76093817, 25.14188416, 26.47040896, 25.97651933,
       36.35652478, 26.0975912 , 23.6416178 , 24.39887199, 20.21195358,
       27.80846468, 22.44206834, 23.07667801, 18.717314  , 23.84934696,
       21.07461275, 21.28209598, 17.89904991, 26.13645315, 12.31661154,
       15.55948057])

In [18]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.20,random_state=101,shuffle=True)

In [19]:
error = y-y_pred

In [20]:
error

0     10.258747
1      7.624608
2      7.734060
3      3.157963
4      8.331584
        ...
76    15.617904
77     1.298838
78     7.863547
79     7.517122
80    -3.458218
Name: MPG, Length: 81, dtype: float64

In [21]:
error.mean()

np.float64(3.50885301609926e-16)

In [27]:
mean_absolute_error(y,y_pred) #same units

3.267968285420799

In [26]:
mean_squared_error(y,y_pred) #Squared units

18.8971411523431

In [30]:
root_mean_squared_error(y,y_pred) #normalize units

4.347084212704315

In [32]:
r2_score(y,y_pred) #

0.7705372737359844

#### STATSMODEL ---- OLS

In [40]:
linear_stats_model_1 = smf.ols(formula= "MPG ~ HP+WT+SP+VOL",data=cars_data).fit()

In [41]:
print(f"R2Score: {linear_stats_model.rsquared.round(4)}")
print(f"Adjusted R2Score: {linear_stats_model.rsquared_adj.round(4)}")

R2Score: 0.7705
Adjusted R2Score: 0.7585

In [44]:
linear_stats_model_2 = smf.ols(formula= "MPG ~ HP",data=cars_data).fit()
print(f"R2Score: {linear_stats_model_2.rsquared.round(4)}")
print(f"Adjusted R2Score: {linear_stats_model_2.rsquared_adj.round(4)}")

R2Score: 0.5257
Adjusted R2Score: 0.5197

In [45]:
linear_stats_model_3 = smf.ols(formula= "MPG ~ HP+VOL",data=cars_data).fit()
print(f"R2Score: {linear_stats_model_3.rsquared.round(4)}")
print(f"Adjusted R2Score: {linear_stats_model_3.rsquared_adj.round(4)}")

R2Score: 0.7507
Adjusted R2Score: 0.7443

In [46]:
linear_stats_model_4 = smf.ols(formula= "MPG ~ HP+SP+VOL",data=cars_data).fit()
print(f"R2Score: {linear_stats_model_4.rsquared.round(4)}")
print(f"Adjusted R2Score: {linear_stats_model_4.rsquared_adj.round(4)}")

R2Score: 0.7704
Adjusted R2Score: 0.7614

In [47]:
linear_stats_model_5 = smf.ols(formula= "MPG ~ HP+WT+SP+VOL",data=cars_data).fit()
print(f"R2Score: {linear_stats_model_5.rsquared.round(4)}")
print(f"Adjusted R2Score: {linear_stats_model_5.rsquared_adj.round(4)}")

R2Score: 0.7705
Adjusted R2Score: 0.7585