###  DATA PREPROCESSING AND DATA PREPARATION

#### DATA CLEANING - drop, fillna with mean, median,mode imputation, changing dtype
#### DATA TRANSFORMATION 
- if data is continouos = standard scalar, minmax scaler, robust scalar
- if data is diecrete = label encoder , one hot encoder

In [86]:
import pandas as pd
import numpy as np

In [5]:
weather_data = pd.read_csv(filepath_or_buffer="environmental_data.csv")

In [6]:
weather_data.head()

   Unnamed: 0  Ozone  Solar.R  Wind Temp C Month  Day  Year  Temp Weather
0           1   41.0    190.0   7.4     67     5    1  2010    67       S
1           2   36.0    118.0   8.0     72     5    2  2010    72       C
2           3   12.0    149.0  12.6     74     5    3  2010    74      PS
3           4   18.0    313.0  11.5     62     5    4  2010    62       S
4           5    NaN      NaN  14.3     56     5    5  2010    56       S

In [4]:
# weather prediction

In [7]:
# data understanding

In [8]:
weather_data.shape

(158, 10)

In [9]:
weather_data.dtypes

Unnamed: 0      int64
Ozone         float64
Solar.R       float64
Wind          float64
Temp C         object
Month          object
Day             int64
Year            int64
Temp            int64
Weather        object
dtype: object

In [10]:
weather_data.isna().sum()

Unnamed: 0     0
Ozone         38
Solar.R        7
Wind           0
Temp C         0
Month          0
Day            0
Year           0
Temp           0
Weather        3
dtype: int64

In [13]:
weather_data.describe(include='all')

,Unnamed: 0,Ozone,Solar.R,Wind,Temp C,Month,Day,Year,Temp,Weather
count,158.000000,120.000000,151.000000,158.000000,158,158,158.000000,158.0,158.000000,155
unique,NaN,NaN,NaN,NaN,41,6,NaN,NaN,NaN,3
top,NaN,NaN,NaN,NaN,81,9,NaN,NaN,NaN,S
freq,NaN,NaN,NaN,NaN,11,34,NaN,NaN,NaN,59
mean,79.500000,41.583333,185.403974,9.957595,NaN,NaN,16.006329,2010.0,77.727848,NaN
std,45.754781,32.620709,88.723103,3.511261,NaN,NaN,8.997166,0.0,9.377877,NaN
min,1.000000,1.000000,7.000000,1.700000,NaN,NaN,1.000000,2010.0,56.000000,NaN
25%,40.250000,18.000000,119.000000,7.400000,NaN,NaN,8.000000,2010.0,72.000000,NaN
50%,79.500000,30.500000,197.000000,9.700000,NaN,NaN,16.000000,2010.0,78.500000,NaN
75%,118.750000,61.500000,257.000000,11.875000,NaN,NaN,24.000000,2010.0,84.000000,NaN
max,158.000000,168.000000,334.000000,20.700000,NaN,NaN,31.000000,2010.0,97.000000,NaN

In [14]:
weather_data['Weather'].unique()

array(['S', 'C', 'PS', nan], dtype=object)

In [15]:
weather_data['Weather'].value_counts()

Weather
S     59
C     49
PS    47
Name: count, dtype: int64

In [16]:
weather_data['Weather'].value_counts(dropna=False)

Weather
S      59
C      49
PS     47
NaN     3
Name: count, dtype: int64

In [17]:
# data cleaning

In [18]:
weather_data.drop(labels=["Unnamed: 0","Temp C"],axis=1,inplace=True)

In [19]:
weather_data.head()

   Ozone  Solar.R  Wind Month  Day  Year  Temp Weather
0   41.0    190.0   7.4     5    1  2010    67       S
1   36.0    118.0   8.0     5    2  2010    72       C
2   12.0    149.0  12.6     5    3  2010    74      PS
3   18.0    313.0  11.5     5    4  2010    62       S
4    NaN      NaN  14.3     5    5  2010    56       S

In [20]:
weather_data.dtypes

Ozone      float64
Solar.R    float64
Wind       float64
Month       object
Day          int64
Year         int64
Temp         int64
Weather     object
dtype: object

In [21]:
# convt into numeric values(all)

In [23]:
weather_data.isna().sum()

Ozone      38
Solar.R     7
Wind        0
Month       0
Day         0
Year        0
Temp        0
Weather     3
dtype: int64

In [24]:
38/158

0.24050632911392406

In [25]:
# 25% of null values are present in Ozone feature

In [27]:
del weather_data["Ozone"]

In [28]:
weather_data.isna().sum()

Solar.R    7
Wind       0
Month      0
Day        0
Year       0
Temp       0
Weather    3
dtype: int64

In [29]:
weather_data.shape

(158, 7)

In [30]:
weather_data[weather_data['Solar.R'].isna()]

    Solar.R  Wind Month  Day  Year  Temp Weather
4       NaN  14.3     5    5  2010    56       S
5       NaN  14.9     5    6  2010    66       C
10      NaN   6.9     5   11  2010    74       C
26      NaN   8.0     5   27  2010    57      PS
95      NaN   6.9     8    4  2010    86     NaN
96      NaN   7.4     8    5  2010    85       S
97      NaN   4.6     8    6  2010    87       C

In [31]:
weather_data[weather_data['Weather'].isna()]

    Solar.R  Wind Month  Day  Year  Temp Weather
87     82.0  12.0     7   27  2010    86     NaN
93     24.0  13.8     8    2  2010    81     NaN
95      NaN   6.9     8    4  2010    86     NaN

In [33]:
weather_data.groupby("Weather")['Solar.R'].mean().round() # take the avaerage using groupby fucntion

Weather
C     192.0
PS    174.0
S     193.0
Name: Solar.R, dtype: float64

In [36]:
weather_data["Solar.R"] = weather_data.groupby("Weather")['Solar.R'].transform(lambda x:x.fillna(x.mean().round()))

In [37]:
weather_data.shape

(158, 7)

In [39]:
weather_data.isna().sum()

Solar.R    3
Wind       0
Month      0
Day        0
Year       0
Temp       0
Weather    3
dtype: int64

In [40]:
weather_data[weather_data["Weather"].isna()]

    Solar.R  Wind Month  Day  Year  Temp Weather
87      NaN  12.0     7   27  2010    86     NaN
93      NaN  13.8     8    2  2010    81     NaN
95      NaN   6.9     8    4  2010    86     NaN

In [41]:
weather_data.dropna(inplace=True)

In [42]:
weather_data.isnull().sum()

Solar.R    0
Wind       0
Month      0
Day        0
Year       0
Temp       0
Weather    0
dtype: int64

In [43]:
weather_data.shape

(155, 7)

In [45]:
weather_data['Month'].unique()

array(['5', 'May', '6', '7', '8', '9'], dtype=object)

In [47]:
weather_data['Month'].replace(to_replace="May",value=5,inplace=True)

In [49]:
weather_data.dtypes

Solar.R    float64
Wind       float64
Month       object
Day          int64
Year         int64
Temp         int64
Weather     object
dtype: object

In [50]:
weather_data["Month"] = weather_data["Month"].astype('int')

In [51]:
weather_data.dtypes

Solar.R    float64
Wind       float64
Month        int64
Day          int64
Year         int64
Temp         int64
Weather     object
dtype: object

In [52]:
weather_data['Weather'].unique()

array(['S', 'C', 'PS'], dtype=object)

In [53]:
### Data transformation techniques

In [55]:
"""continuous - std scalar,minmax scalar, robust scalar\n
discrete - one hot encoder, label encoder"""

'continuous - std scalar,minmax scalar, robust scalar\n\ndiscrete - one hot encoder, label encoder'

In [57]:
weather_data.head()

   Solar.R  Wind  Month  Day  Year  Temp Weather
0    190.0   7.4      5    1  2010    67       S
1    118.0   8.0      5    2  2010    72       C
2    149.0  12.6      5    3  2010    74      PS
3    313.0  11.5      5    4  2010    62       S
4    193.0  14.3      5    5  2010    56       S

In [58]:
weather_data_copy = weather_data.copy()

In [61]:
weather_data_copy.isna().sum()

Solar.R    0
Wind       0
Month      0
Day        0
Year       0
Temp       0
Weather    0
dtype: int64

In [63]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

In [66]:
le_encoder = LabelEncoder()
weather_data_copy['Weather'] = le_encoder.fit_transform(weather_data_copy["Weather"])

In [67]:
weather_data_copy.dtypes

Solar.R    float64
Wind       float64
Month        int64
Day          int64
Year         int64
Temp         int64
Weather      int64
dtype: object

#### One hot encoder - 
- This can be achieved by using any of the following 2 libraries:

- pandas = pd.get_dummies()

- sklearn = OneHotEncoder()

In [72]:
weather_data_copy_2 = weather_data_copy.copy()

In [73]:
weather_data_copy_2 = pd.get_dummies(data =weather_data_copy_2,columns=["Weather"],dtype="int")

In [74]:
weather_data_copy_2

     Solar.R  Wind  Month  Day  Year  Temp  Weather_0  Weather_1  Weather_2
0      190.0   7.4      5    1  2010    67          0          0          1
1      118.0   8.0      5    2  2010    72          1          0          0
2      149.0  12.6      5    3  2010    74          0          1          0
3      313.0  11.5      5    4  2010    62          0          0          1
4      193.0  14.3      5    5  2010    56          0          0          1
..       ...   ...    ...  ...   ...   ...        ...        ...        ...
153    190.0   7.4      5    1  2010    67          1          0          0
154    193.0   6.9      9   26  2010    70          0          1          0
155    145.0  13.2      9   27  2010    77          0          0          1
156    191.0  14.3      9   28  2010    75          0          0          1
157    131.0   8.0      9   29  2010    76          1          0          0

[155 rows x 9 columns]

In [76]:
weather_data_copy_2.dtypes

Solar.R      float64
Wind         float64
Month          int64
Day            int64
Year           int64
Temp           int64
Weather_0      int64
Weather_1      int64
Weather_2      int64
dtype: object

In [89]:
weather_data_copy_3 = weather_data_copy.copy()

In [90]:
ohe = OneHotEncoder()

In [91]:
weather_data_copy_3 = ohe.fit_transform(weather_data_copy_3[["Weather"]]).toarray()

In [92]:
weather_data_copy_3

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [93]:
# how to choose b/w one hot encoder and label encoder